
import React from 'react';
import type { SearchData } from '../types';
import LoadingSkeleton from './LoadingSkeleton';
import ErrorDisplay from './ErrorDisplay';
import IntentCard from './IntentCard';
import ResultItem from './ResultItem';
import Pagination from './Pagination';
import { Search } from './icons';

interface ResultsViewProps {
  loading: boolean;
  error: string | null;
  data: SearchData | null;
  currentPage: number;
  resultsPerPage: number;
  paginate: (page: number) => void;
}

const ResultsView: React.FC<ResultsViewProps> = ({ loading, error, data, currentPage, resultsPerPage, paginate }) => {
  if (loading && !data) {
    return <LoadingSkeleton />;
  }

  if (error) {
    return <ErrorDisplay error={error} />;
  }

  if (!data) {
    return null; // Don't show anything before the first search
  }

  const indexOfLastResult = currentPage * resultsPerPage;
  const indexOfFirstResult = indexOfLastResult - resultsPerPage;
  const currentResults = data.results.slice(indexOfFirstResult, indexOfLastResult);
  const totalPages = Math.ceil(data.results.length / resultsPerPage);

  return (
    <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
      <IntentCard intent={data.search_intent} type={data.intent_type} />

      <div className="space-y-6">
        <div className="flex items-center justify-between">
          <h3 className="text-xl font-bold text-slate-800 flex items-center gap-2">
            <Search className="w-5 h-5 text-slate-400" />
            Analyzed Search Results
            <span className="text-sm font-normal text-slate-400 ml-2">
              ({data.results.length} found)
            </span>
          </h3>
        </div>

        {currentResults.length > 0 ? (
          currentResults.map((result, idx) => (
            <ResultItem key={indexOfFirstResult + idx} result={result} rank={indexOfFirstResult + idx + 1} />
          ))
        ) : (
          <div className="text-center py-8 text-slate-500">
            No results found for this page.
          </div>
        )}

        {totalPages > 1 && (
          <Pagination
            currentPage={currentPage}
            totalPages={totalPages}
            paginate={paginate}
          />
        )}
      </div>

      <div className="text-center pt-8 pb-4">
        <p className="text-xs text-slate-400">
          Results retrieved via Google Search Grounding. Analysis generated by Gemini 2.5 Flash.
        </p>
      </div>
    </div>
  );
};

export default ResultsView;
